import PDFDocument from "pdfkit";
import { formatCurrencyForPdf, formatDate } from "./format";

const PAGE_MARGIN = 40;
const INDIGO = "#4f46e5";
const SLATE_900 = "#0f172a";
const SLATE_500 = "#64748b";
const SLATE_200 = "#e2e8f0";
const ROSE_600 = "#e11d48";
const EMERALD_600 = "#059669";

function newDocument() {
  return new PDFDocument({ size: "A4", margin: PAGE_MARGIN, bufferPages: true });
}

function drawBrandHeader(doc, { title, metaLines }) {
  const pageWidth = doc.page.width - PAGE_MARGIN * 2;

  doc
    .rect(PAGE_MARGIN, PAGE_MARGIN, 22, 22)
    .fill(INDIGO);
  doc
    .fillColor("#ffffff")
    .fontSize(9)
    .font("Helvetica-Bold")
    .text("PT", PAGE_MARGIN, PAGE_MARGIN + 6, { width: 22, align: "center" });

  doc
    .fillColor(SLATE_900)
    .font("Helvetica-Bold")
    .fontSize(11)
    .text("Payment Tracker", PAGE_MARGIN + 30, PAGE_MARGIN + 4);

  doc
    .fillColor(SLATE_900)
    .font("Helvetica-Bold")
    .fontSize(18)
    .text(title, PAGE_MARGIN, PAGE_MARGIN + 34, { width: pageWidth });

  let y = doc.y + 4;
  doc.font("Helvetica").fontSize(9.5).fillColor(SLATE_500);
  for (const line of metaLines) {
    doc.text(line, PAGE_MARGIN, y, { width: pageWidth });
    y = doc.y + 2;
  }

  y += 6;
  doc.moveTo(PAGE_MARGIN, y).lineTo(PAGE_MARGIN + pageWidth, y).strokeColor(SLATE_200).stroke();
  return y + 16;
}

function drawSummaryRow(doc, startY, boxes) {
  const pageWidth = doc.page.width - PAGE_MARGIN * 2;
  const gap = 12;
  const boxWidth = (pageWidth - gap * (boxes.length - 1)) / boxes.length;
  const boxHeight = 48;

  boxes.forEach((box, i) => {
    const x = PAGE_MARGIN + i * (boxWidth + gap);
    doc
      .roundedRect(x, startY, boxWidth, boxHeight, 4)
      .fillAndStroke("#f8fafc", SLATE_200);
    doc
      .fillColor(SLATE_500)
      .font("Helvetica")
      .fontSize(8)
      .text(box.label.toUpperCase(), x + 10, startY + 8, { width: boxWidth - 20 });
    doc
      .fillColor(box.color || SLATE_900)
      .font("Helvetica-Bold")
      .fontSize(13)
      .text(box.value, x + 10, startY + 22, { width: boxWidth - 20 });
  });

  return startY + boxHeight + 20;
}

function ensureSpace(doc, y, needed, onNewPage) {
  const bottom = doc.page.height - doc.page.margins.bottom;
  if (y + needed > bottom) {
    doc.addPage();
    return onNewPage ? onNewPage(doc) : PAGE_MARGIN;
  }
  return y;
}

function drawTableHeader(doc, y, columns) {
  const rowHeight = 20;
  doc.rect(PAGE_MARGIN, y, columns.reduce((s, c) => s + c.width, 0), rowHeight).fill("#eef2ff");
  let x = PAGE_MARGIN;
  doc.font("Helvetica-Bold").fontSize(8.5).fillColor(INDIGO);
  for (const col of columns) {
    doc.text(col.label, x + 6, y + 6, { width: col.width - 10, align: col.align || "left" });
    x += col.width;
  }
  return y + rowHeight;
}

function drawTable(doc, { startY, columns, rows, zebra = true, sectionTitle }) {
  let y = startY;

  if (sectionTitle) {
    doc.font("Helvetica-Bold").fontSize(11).fillColor(SLATE_900).text(sectionTitle, PAGE_MARGIN, y);
    y = doc.y + 8;
  }

  const redraw = (d) => {
    let ny = PAGE_MARGIN;
    if (sectionTitle) {
      d.font("Helvetica-Bold").fontSize(11).fillColor(SLATE_900).text(`${sectionTitle} (continued)`, PAGE_MARGIN, ny);
      ny = d.y + 8;
    }
    return drawTableHeader(d, ny, columns);
  };

  y = drawTableHeader(doc, y, columns);

  const rowHeight = 18;
  rows.forEach((row, idx) => {
    y = ensureSpace(doc, y, rowHeight, redraw);

    if (zebra && idx % 2 === 1) {
      doc.rect(PAGE_MARGIN, y, columns.reduce((s, c) => s + c.width, 0), rowHeight).fill("#f8fafc");
    }

    let x = PAGE_MARGIN;
    doc.font("Helvetica").fontSize(8.5);
    for (const col of columns) {
      const value = row[col.key] ?? "-";
      doc.fillColor(col.colorKey && row[col.colorKey] ? row[col.colorKey] : SLATE_900);
      doc.text(String(value), x + 6, y + 5, {
        width: col.width - 10,
        align: col.align || "left",
        ellipsis: true,
      });
      x += col.width;
    }
    y += rowHeight;
  });

  return y;
}

function drawFootersAndPageNumbers(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const bottom = doc.page.height - PAGE_MARGIN + 14;
    // Writing inside the bottom margin band can otherwise trigger pdfkit's
    // automatic pagination mid-loop, silently inserting extra blank pages.
    doc.page.margins.bottom = 0;
    doc
      .font("Helvetica")
      .fontSize(7.5)
      .fillColor(SLATE_500)
      .text("Generated by Payment Tracker", PAGE_MARGIN, bottom, {
        width: 250,
        align: "left",
        lineBreak: false,
      });
    doc.text(
      `Page ${i - range.start + 1} of ${range.count}`,
      doc.page.width - PAGE_MARGIN - 150,
      bottom,
      { width: 150, align: "right", lineBreak: false }
    );
  }
}

function ledgerRowsForPdf(ledger, { showProject = false } = {}) {
  return ledger.map((entry) => ({
    date: formatDate(entry.date),
    project: entry.project || "",
    description: entry.description,
    debit: entry.debit ? formatCurrencyForPdf(entry.debit) : "-",
    credit: entry.credit ? formatCurrencyForPdf(entry.credit) : "-",
    balance: formatCurrencyForPdf(entry.runningBalance),
    debitColor: entry.debit ? ROSE_600 : SLATE_500,
    creditColor: entry.credit ? EMERALD_600 : SLATE_500,
  }));
}

export async function generateProjectStatementPdf(statement) {
  const doc = newDocument();
  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));

  const { project, ledger, generatedAt } = statement;

  let y = drawBrandHeader(doc, {
    title: "Statement of Account",
    metaLines: [
      `Project: ${project.name}`,
      `Contractor: ${project.contractor}${project.phone ? ` · ${project.phone}` : ""}`,
      `Generated: ${generatedAt.toLocaleString("en-IN")}`,
    ],
  });

  y = drawSummaryRow(doc, y, [
    { label: "Total Amount", value: formatCurrencyForPdf(project.totalAmount) },
    { label: "Total Payment", value: formatCurrencyForPdf(project.totalPayment), color: EMERALD_600 },
    {
      label: "Balance",
      value: formatCurrencyForPdf(project.balance),
      color: project.balance > 0 ? ROSE_600 : SLATE_900,
    },
  ]);

  const columns = [
    { key: "date", label: "Date", width: 70 },
    { key: "description", label: "Description", width: 230 },
    { key: "debit", label: "Invoiced", width: 70, align: "right", colorKey: "debitColor" },
    { key: "credit", label: "Paid", width: 70, align: "right", colorKey: "creditColor" },
    { key: "balance", label: "Balance", width: 75, align: "right" },
  ];

  drawTable(doc, {
    startY: y,
    columns,
    rows: ledgerRowsForPdf(ledger),
    sectionTitle: "Transaction Ledger",
  });

  drawFootersAndPageNumbers(doc);
  doc.end();

  return new Promise((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
}

export async function generateContractorStatementPdf(statement) {
  const doc = newDocument();
  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));

  const { contractor, projects, ledger, generatedAt } = statement;

  let y = drawBrandHeader(doc, {
    title: "Statement of Account",
    metaLines: [
      `Contractor: ${contractor.name}${contractor.phone ? ` · ${contractor.phone}` : ""}`,
      `Projects: ${projects.length}`,
      `Generated: ${generatedAt.toLocaleString("en-IN")}`,
    ],
  });

  y = drawSummaryRow(doc, y, [
    { label: "Total Amount", value: formatCurrencyForPdf(contractor.totalAmount) },
    { label: "Total Payment", value: formatCurrencyForPdf(contractor.totalPayment), color: EMERALD_600 },
    {
      label: "Balance",
      value: formatCurrencyForPdf(contractor.totalBalance),
      color: contractor.totalBalance > 0 ? ROSE_600 : SLATE_900,
    },
  ]);

  const projectColumns = [
    { key: "name", label: "Project", width: 200 },
    { key: "status", label: "Status", width: 65 },
    { key: "total", label: "Total", width: 85, align: "right" },
    { key: "paid", label: "Paid", width: 85, align: "right", colorKey: "paidColor" },
    { key: "balance", label: "Balance", width: 80, align: "right", colorKey: "balanceColor" },
  ];

  const projectRows = projects.map((p) => ({
    name: p.name,
    status: p.active ? "Active" : "Closed",
    total: formatCurrencyForPdf(p.totalAmount),
    paid: formatCurrencyForPdf(p.totalPayment),
    balance: formatCurrencyForPdf(p.balance),
    paidColor: EMERALD_600,
    balanceColor: p.balance > 0 ? ROSE_600 : SLATE_900,
  }));

  y = drawTable(doc, {
    startY: y,
    columns: projectColumns,
    rows: projectRows,
    sectionTitle: "Projects Summary",
  });

  y += 16;
  y = ensureSpace(doc, y, 40, () => PAGE_MARGIN);

  const ledgerColumns = [
    { key: "date", label: "Date", width: 62 },
    { key: "project", label: "Project", width: 108 },
    { key: "description", label: "Description", width: 165 },
    { key: "debit", label: "Invoiced", width: 60, align: "right", colorKey: "debitColor" },
    { key: "credit", label: "Paid", width: 60, align: "right", colorKey: "creditColor" },
    { key: "balance", label: "Balance", width: 60, align: "right" },
  ];

  drawTable(doc, {
    startY: y,
    columns: ledgerColumns,
    rows: ledgerRowsForPdf(ledger, { showProject: true }),
    sectionTitle: "Combined Transaction Ledger (all projects)",
  });

  drawFootersAndPageNumbers(doc);
  doc.end();

  return new Promise((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
}
